version: '3.4'
 
networks:
    TetePizza:       
 
services:
    db:
        #container_name: dbContainer
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    api:
    
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: Api/Dockerfile
        depends_on:
            - db
  